export class PermissionYachtsConfig {

	public MANAGE_YACHT = 'MANAGE_YACHT';
	public DELETE_YACHT = 'DELETE_YACHT';

	public MANAGE_YACHT_RESERVATION = 'MANAGE_YACHT_RESERVATION';
	public DELETE_YACHT_RESERVATION = 'DELETE_YACHT_RESERVATION';


	public YACHTS_PERMISSIONS = [
		this.MANAGE_YACHT,
		this.DELETE_YACHT,
	];

	public YACHTS_RESERVATION_PERMISSIONS = [
		this.MANAGE_YACHT_RESERVATION,
		this.DELETE_YACHT_RESERVATION,
	];

}
