export class PermissionWaterSportConfig {

	public MANAGE_WATER_SPORT = 'MANAGE_WATERSPORT';
	public DELETE_WATER_SPORT = 'DELETE_WATERSPORT';

	public MANAGE_WATER_SPORT_RESERVATION = 'MANAGE_WATERSPORT_RESERVATION';
	public DELETE_WATER_SPORT_RESERVATION = 'DELETE_WATERSPORT_RESERVATION';


	public WATER_SPORTS_PERMISSIONS = [
		this.MANAGE_WATER_SPORT,
		this.DELETE_WATER_SPORT,
	];

	public WATER_SPORTS_RESERVATION_PERMISSIONS = [
		this.MANAGE_WATER_SPORT_RESERVATION,
		this.DELETE_WATER_SPORT_RESERVATION,
	];

}
